include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    require_trailing_commas: true
